list: $/trka/marketplace/models/categrory/columns.yaml
modelClass: trka\Marketplace\Models\Categrory
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'trka/marketplace/categories/update/:id'
