list: $/trka/marketplace/models/downloadtags/columns.yaml
modelClass: trka\Marketplace\Models\DownloadTags
title: DownloadTags
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'trka/marketplace/downloadtags/update/:id'
