list: $/trka/marketplace/models/downloads/columns.yaml
modelClass: trka\Marketplace\Models\Downloads
title: Downloads
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'trka/marketplace/downloads/update/:id'
